#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyELibwebservice.App_Code
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MyELib")]
	public partial class myelibDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbook_mast(book_mast instance);
    partial void Updatebook_mast(book_mast instance);
    partial void Deletebook_mast(book_mast instance);
    partial void Insertbookcopy_mast(bookcopy_mast instance);
    partial void Updatebookcopy_mast(bookcopy_mast instance);
    partial void Deletebookcopy_mast(bookcopy_mast instance);
    partial void Insertreq_mast(req_mast instance);
    partial void Updatereq_mast(req_mast instance);
    partial void Deletereq_mast(req_mast instance);
    partial void Insertstud_mast(stud_mast instance);
    partial void Updatestud_mast(stud_mast instance);
    partial void Deletestud_mast(stud_mast instance);
    partial void Inserttrans_mast(trans_mast instance);
    partial void Updatetrans_mast(trans_mast instance);
    partial void Deletetrans_mast(trans_mast instance);
    #endregion
		
		public myelibDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MyELibConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public myelibDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myelibDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myelibDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myelibDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<book_mast> book_masts
		{
			get
			{
				return this.GetTable<book_mast>();
			}
		}
		
		public System.Data.Linq.Table<bookcopy_mast> bookcopy_masts
		{
			get
			{
				return this.GetTable<bookcopy_mast>();
			}
		}
		
		public System.Data.Linq.Table<notice_mast> notice_masts
		{
			get
			{
				return this.GetTable<notice_mast>();
			}
		}
		
		public System.Data.Linq.Table<req_mast> req_masts
		{
			get
			{
				return this.GetTable<req_mast>();
			}
		}
		
		public System.Data.Linq.Table<stud_mast> stud_masts
		{
			get
			{
				return this.GetTable<stud_mast>();
			}
		}
		
		public System.Data.Linq.Table<trans_mast> trans_masts
		{
			get
			{
				return this.GetTable<trans_mast>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.book_mast")]
	public partial class book_mast : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _bk_id;
		
		private string _bk_name;
		
		private string _bk_auther;
		
		private string _bk_publisher;
		
		private string _bk_desc;
		
		private decimal _bk_stock;
		
		private decimal _bk_avail;
		
		private EntitySet<req_mast> _req_masts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbk_idChanging(decimal value);
    partial void Onbk_idChanged();
    partial void Onbk_nameChanging(string value);
    partial void Onbk_nameChanged();
    partial void Onbk_autherChanging(string value);
    partial void Onbk_autherChanged();
    partial void Onbk_publisherChanging(string value);
    partial void Onbk_publisherChanged();
    partial void Onbk_descChanging(string value);
    partial void Onbk_descChanged();
    partial void Onbk_stockChanging(decimal value);
    partial void Onbk_stockChanged();
    partial void Onbk_availChanging(decimal value);
    partial void Onbk_availChanged();
    #endregion
		
		public book_mast()
		{
			this._req_masts = new EntitySet<req_mast>(new Action<req_mast>(this.attach_req_masts), new Action<req_mast>(this.detach_req_masts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk_id", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal bk_id
		{
			get
			{
				return this._bk_id;
			}
			set
			{
				if ((this._bk_id != value))
				{
					this.Onbk_idChanging(value);
					this.SendPropertyChanging();
					this._bk_id = value;
					this.SendPropertyChanged("bk_id");
					this.Onbk_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string bk_name
		{
			get
			{
				return this._bk_name;
			}
			set
			{
				if ((this._bk_name != value))
				{
					this.Onbk_nameChanging(value);
					this.SendPropertyChanging();
					this._bk_name = value;
					this.SendPropertyChanged("bk_name");
					this.Onbk_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk_auther", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string bk_auther
		{
			get
			{
				return this._bk_auther;
			}
			set
			{
				if ((this._bk_auther != value))
				{
					this.Onbk_autherChanging(value);
					this.SendPropertyChanging();
					this._bk_auther = value;
					this.SendPropertyChanged("bk_auther");
					this.Onbk_autherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk_publisher", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string bk_publisher
		{
			get
			{
				return this._bk_publisher;
			}
			set
			{
				if ((this._bk_publisher != value))
				{
					this.Onbk_publisherChanging(value);
					this.SendPropertyChanging();
					this._bk_publisher = value;
					this.SendPropertyChanged("bk_publisher");
					this.Onbk_publisherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk_desc", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string bk_desc
		{
			get
			{
				return this._bk_desc;
			}
			set
			{
				if ((this._bk_desc != value))
				{
					this.Onbk_descChanging(value);
					this.SendPropertyChanging();
					this._bk_desc = value;
					this.SendPropertyChanged("bk_desc");
					this.Onbk_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk_stock", DbType="Decimal(18,0) NOT NULL")]
		public decimal bk_stock
		{
			get
			{
				return this._bk_stock;
			}
			set
			{
				if ((this._bk_stock != value))
				{
					this.Onbk_stockChanging(value);
					this.SendPropertyChanging();
					this._bk_stock = value;
					this.SendPropertyChanged("bk_stock");
					this.Onbk_stockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk_avail", DbType="Decimal(18,0) NOT NULL")]
		public decimal bk_avail
		{
			get
			{
				return this._bk_avail;
			}
			set
			{
				if ((this._bk_avail != value))
				{
					this.Onbk_availChanging(value);
					this.SendPropertyChanging();
					this._bk_avail = value;
					this.SendPropertyChanged("bk_avail");
					this.Onbk_availChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="book_mast_req_mast", Storage="_req_masts", ThisKey="bk_id", OtherKey="bk_id")]
		public EntitySet<req_mast> req_masts
		{
			get
			{
				return this._req_masts;
			}
			set
			{
				this._req_masts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_req_masts(req_mast entity)
		{
			this.SendPropertyChanging();
			entity.book_mast = this;
		}
		
		private void detach_req_masts(req_mast entity)
		{
			this.SendPropertyChanging();
			entity.book_mast = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bookcopy_mast")]
	public partial class bookcopy_mast : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _bk_id;
		
		private decimal _bk_seqno;
		
		private decimal _bk_avail;
		
		private string _status;
		
		private EntitySet<trans_mast> _trans_masts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbk_idChanging(decimal value);
    partial void Onbk_idChanged();
    partial void Onbk_seqnoChanging(decimal value);
    partial void Onbk_seqnoChanged();
    partial void Onbk_availChanging(decimal value);
    partial void Onbk_availChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public bookcopy_mast()
		{
			this._trans_masts = new EntitySet<trans_mast>(new Action<trans_mast>(this.attach_trans_masts), new Action<trans_mast>(this.detach_trans_masts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk_id", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal bk_id
		{
			get
			{
				return this._bk_id;
			}
			set
			{
				if ((this._bk_id != value))
				{
					this.Onbk_idChanging(value);
					this.SendPropertyChanging();
					this._bk_id = value;
					this.SendPropertyChanged("bk_id");
					this.Onbk_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk_seqno", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal bk_seqno
		{
			get
			{
				return this._bk_seqno;
			}
			set
			{
				if ((this._bk_seqno != value))
				{
					this.Onbk_seqnoChanging(value);
					this.SendPropertyChanging();
					this._bk_seqno = value;
					this.SendPropertyChanged("bk_seqno");
					this.Onbk_seqnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk_avail", DbType="Decimal(18,0) NOT NULL")]
		public decimal bk_avail
		{
			get
			{
				return this._bk_avail;
			}
			set
			{
				if ((this._bk_avail != value))
				{
					this.Onbk_availChanging(value);
					this.SendPropertyChanging();
					this._bk_avail = value;
					this.SendPropertyChanged("bk_avail");
					this.Onbk_availChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bookcopy_mast_trans_mast", Storage="_trans_masts", ThisKey="bk_id,bk_seqno", OtherKey="bk_id,bk_seq_id")]
		public EntitySet<trans_mast> trans_masts
		{
			get
			{
				return this._trans_masts;
			}
			set
			{
				this._trans_masts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_trans_masts(trans_mast entity)
		{
			this.SendPropertyChanging();
			entity.bookcopy_mast = this;
		}
		
		private void detach_trans_masts(trans_mast entity)
		{
			this.SendPropertyChanging();
			entity.bookcopy_mast = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.notice_mast")]
	public partial class notice_mast
	{
		
		private string _stud_libcard_no;
		
		private decimal _bk_id;
		
		private System.DateTime _ntc_date_time;
		
		public notice_mast()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_libcard_no", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string stud_libcard_no
		{
			get
			{
				return this._stud_libcard_no;
			}
			set
			{
				if ((this._stud_libcard_no != value))
				{
					this._stud_libcard_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk_id", DbType="Decimal(18,0) NOT NULL")]
		public decimal bk_id
		{
			get
			{
				return this._bk_id;
			}
			set
			{
				if ((this._bk_id != value))
				{
					this._bk_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ntc_date_time", DbType="DateTime NOT NULL")]
		public System.DateTime ntc_date_time
		{
			get
			{
				return this._ntc_date_time;
			}
			set
			{
				if ((this._ntc_date_time != value))
				{
					this._ntc_date_time = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[req-mast]")]
	public partial class req_mast : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _req_id;
		
		private decimal _bk_id;
		
		private decimal _stud_enroll_no;
		
		private string _stud_libcard_no;
		
		private System.DateTime _req_date;
		
		private string _req_status;
		
		private EntityRef<book_mast> _book_mast;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onreq_idChanging(decimal value);
    partial void Onreq_idChanged();
    partial void Onbk_idChanging(decimal value);
    partial void Onbk_idChanged();
    partial void Onstud_enroll_noChanging(decimal value);
    partial void Onstud_enroll_noChanged();
    partial void Onstud_libcard_noChanging(string value);
    partial void Onstud_libcard_noChanged();
    partial void Onreq_dateChanging(System.DateTime value);
    partial void Onreq_dateChanged();
    partial void Onreq_statusChanging(string value);
    partial void Onreq_statusChanged();
    #endregion
		
		public req_mast()
		{
			this._book_mast = default(EntityRef<book_mast>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_req_id", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal req_id
		{
			get
			{
				return this._req_id;
			}
			set
			{
				if ((this._req_id != value))
				{
					this.Onreq_idChanging(value);
					this.SendPropertyChanging();
					this._req_id = value;
					this.SendPropertyChanged("req_id");
					this.Onreq_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk_id", DbType="Decimal(18,0) NOT NULL")]
		public decimal bk_id
		{
			get
			{
				return this._bk_id;
			}
			set
			{
				if ((this._bk_id != value))
				{
					if (this._book_mast.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onbk_idChanging(value);
					this.SendPropertyChanging();
					this._bk_id = value;
					this.SendPropertyChanged("bk_id");
					this.Onbk_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_enroll_no", DbType="Decimal(18,0) NOT NULL")]
		public decimal stud_enroll_no
		{
			get
			{
				return this._stud_enroll_no;
			}
			set
			{
				if ((this._stud_enroll_no != value))
				{
					this.Onstud_enroll_noChanging(value);
					this.SendPropertyChanging();
					this._stud_enroll_no = value;
					this.SendPropertyChanged("stud_enroll_no");
					this.Onstud_enroll_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_libcard_no", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string stud_libcard_no
		{
			get
			{
				return this._stud_libcard_no;
			}
			set
			{
				if ((this._stud_libcard_no != value))
				{
					this.Onstud_libcard_noChanging(value);
					this.SendPropertyChanging();
					this._stud_libcard_no = value;
					this.SendPropertyChanged("stud_libcard_no");
					this.Onstud_libcard_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_req_date", DbType="DateTime NOT NULL")]
		public System.DateTime req_date
		{
			get
			{
				return this._req_date;
			}
			set
			{
				if ((this._req_date != value))
				{
					this.Onreq_dateChanging(value);
					this.SendPropertyChanging();
					this._req_date = value;
					this.SendPropertyChanged("req_date");
					this.Onreq_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_req_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string req_status
		{
			get
			{
				return this._req_status;
			}
			set
			{
				if ((this._req_status != value))
				{
					this.Onreq_statusChanging(value);
					this.SendPropertyChanging();
					this._req_status = value;
					this.SendPropertyChanged("req_status");
					this.Onreq_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="book_mast_req_mast", Storage="_book_mast", ThisKey="bk_id", OtherKey="bk_id", IsForeignKey=true)]
		public book_mast book_mast
		{
			get
			{
				return this._book_mast.Entity;
			}
			set
			{
				book_mast previousValue = this._book_mast.Entity;
				if (((previousValue != value) 
							|| (this._book_mast.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._book_mast.Entity = null;
						previousValue.req_masts.Remove(this);
					}
					this._book_mast.Entity = value;
					if ((value != null))
					{
						value.req_masts.Add(this);
						this._bk_id = value.bk_id;
					}
					else
					{
						this._bk_id = default(decimal);
					}
					this.SendPropertyChanged("book_mast");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stud_mast")]
	public partial class stud_mast : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _stud_enroll_no;
		
		private string _stud_libcard_no;
		
		private string _stud_fname;
		
		private string _stud_mname;
		
		private string _stud_lname;
		
		private string _stud_class;
		
		private string _stud_dept;
		
		private string _stud_email;
		
		private string _stud_mob_no;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstud_enroll_noChanging(string value);
    partial void Onstud_enroll_noChanged();
    partial void Onstud_libcard_noChanging(string value);
    partial void Onstud_libcard_noChanged();
    partial void Onstud_fnameChanging(string value);
    partial void Onstud_fnameChanged();
    partial void Onstud_mnameChanging(string value);
    partial void Onstud_mnameChanged();
    partial void Onstud_lnameChanging(string value);
    partial void Onstud_lnameChanged();
    partial void Onstud_classChanging(string value);
    partial void Onstud_classChanged();
    partial void Onstud_deptChanging(string value);
    partial void Onstud_deptChanged();
    partial void Onstud_emailChanging(string value);
    partial void Onstud_emailChanged();
    partial void Onstud_mob_noChanging(string value);
    partial void Onstud_mob_noChanged();
    #endregion
		
		public stud_mast()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_enroll_no", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stud_enroll_no
		{
			get
			{
				return this._stud_enroll_no;
			}
			set
			{
				if ((this._stud_enroll_no != value))
				{
					this.Onstud_enroll_noChanging(value);
					this.SendPropertyChanging();
					this._stud_enroll_no = value;
					this.SendPropertyChanged("stud_enroll_no");
					this.Onstud_enroll_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_libcard_no", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string stud_libcard_no
		{
			get
			{
				return this._stud_libcard_no;
			}
			set
			{
				if ((this._stud_libcard_no != value))
				{
					this.Onstud_libcard_noChanging(value);
					this.SendPropertyChanging();
					this._stud_libcard_no = value;
					this.SendPropertyChanged("stud_libcard_no");
					this.Onstud_libcard_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stud_fname
		{
			get
			{
				return this._stud_fname;
			}
			set
			{
				if ((this._stud_fname != value))
				{
					this.Onstud_fnameChanging(value);
					this.SendPropertyChanging();
					this._stud_fname = value;
					this.SendPropertyChanged("stud_fname");
					this.Onstud_fnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_mname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stud_mname
		{
			get
			{
				return this._stud_mname;
			}
			set
			{
				if ((this._stud_mname != value))
				{
					this.Onstud_mnameChanging(value);
					this.SendPropertyChanging();
					this._stud_mname = value;
					this.SendPropertyChanged("stud_mname");
					this.Onstud_mnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stud_lname
		{
			get
			{
				return this._stud_lname;
			}
			set
			{
				if ((this._stud_lname != value))
				{
					this.Onstud_lnameChanging(value);
					this.SendPropertyChanging();
					this._stud_lname = value;
					this.SendPropertyChanged("stud_lname");
					this.Onstud_lnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_class", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stud_class
		{
			get
			{
				return this._stud_class;
			}
			set
			{
				if ((this._stud_class != value))
				{
					this.Onstud_classChanging(value);
					this.SendPropertyChanging();
					this._stud_class = value;
					this.SendPropertyChanged("stud_class");
					this.Onstud_classChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_dept", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stud_dept
		{
			get
			{
				return this._stud_dept;
			}
			set
			{
				if ((this._stud_dept != value))
				{
					this.Onstud_deptChanging(value);
					this.SendPropertyChanging();
					this._stud_dept = value;
					this.SendPropertyChanged("stud_dept");
					this.Onstud_deptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stud_email
		{
			get
			{
				return this._stud_email;
			}
			set
			{
				if ((this._stud_email != value))
				{
					this.Onstud_emailChanging(value);
					this.SendPropertyChanging();
					this._stud_email = value;
					this.SendPropertyChanged("stud_email");
					this.Onstud_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_mob_no", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stud_mob_no
		{
			get
			{
				return this._stud_mob_no;
			}
			set
			{
				if ((this._stud_mob_no != value))
				{
					this.Onstud_mob_noChanging(value);
					this.SendPropertyChanging();
					this._stud_mob_no = value;
					this.SendPropertyChanged("stud_mob_no");
					this.Onstud_mob_noChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.trans_mast")]
	public partial class trans_mast : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _trans_id;
		
		private decimal _bk_id;
		
		private decimal _bk_seq_id;
		
		private string _stud_libcard_no;
		
		private string _trans_type;
		
		private System.DateTime _issue_date;
		
		private System.DateTime _return_date;
		
		private EntityRef<bookcopy_mast> _bookcopy_mast;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontrans_idChanging(decimal value);
    partial void Ontrans_idChanged();
    partial void Onbk_idChanging(decimal value);
    partial void Onbk_idChanged();
    partial void Onbk_seq_idChanging(decimal value);
    partial void Onbk_seq_idChanged();
    partial void Onstud_libcard_noChanging(string value);
    partial void Onstud_libcard_noChanged();
    partial void Ontrans_typeChanging(string value);
    partial void Ontrans_typeChanged();
    partial void Onissue_dateChanging(System.DateTime value);
    partial void Onissue_dateChanged();
    partial void Onreturn_dateChanging(System.DateTime value);
    partial void Onreturn_dateChanged();
    #endregion
		
		public trans_mast()
		{
			this._bookcopy_mast = default(EntityRef<bookcopy_mast>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trans_id", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal trans_id
		{
			get
			{
				return this._trans_id;
			}
			set
			{
				if ((this._trans_id != value))
				{
					this.Ontrans_idChanging(value);
					this.SendPropertyChanging();
					this._trans_id = value;
					this.SendPropertyChanged("trans_id");
					this.Ontrans_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk_id", DbType="Decimal(18,0) NOT NULL")]
		public decimal bk_id
		{
			get
			{
				return this._bk_id;
			}
			set
			{
				if ((this._bk_id != value))
				{
					if (this._bookcopy_mast.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onbk_idChanging(value);
					this.SendPropertyChanging();
					this._bk_id = value;
					this.SendPropertyChanged("bk_id");
					this.Onbk_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk_seq_id", DbType="Decimal(18,0) NOT NULL")]
		public decimal bk_seq_id
		{
			get
			{
				return this._bk_seq_id;
			}
			set
			{
				if ((this._bk_seq_id != value))
				{
					if (this._bookcopy_mast.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onbk_seq_idChanging(value);
					this.SendPropertyChanging();
					this._bk_seq_id = value;
					this.SendPropertyChanged("bk_seq_id");
					this.Onbk_seq_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_libcard_no", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stud_libcard_no
		{
			get
			{
				return this._stud_libcard_no;
			}
			set
			{
				if ((this._stud_libcard_no != value))
				{
					this.Onstud_libcard_noChanging(value);
					this.SendPropertyChanging();
					this._stud_libcard_no = value;
					this.SendPropertyChanged("stud_libcard_no");
					this.Onstud_libcard_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trans_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string trans_type
		{
			get
			{
				return this._trans_type;
			}
			set
			{
				if ((this._trans_type != value))
				{
					this.Ontrans_typeChanging(value);
					this.SendPropertyChanging();
					this._trans_type = value;
					this.SendPropertyChanged("trans_type");
					this.Ontrans_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_issue_date", DbType="DateTime NOT NULL")]
		public System.DateTime issue_date
		{
			get
			{
				return this._issue_date;
			}
			set
			{
				if ((this._issue_date != value))
				{
					this.Onissue_dateChanging(value);
					this.SendPropertyChanging();
					this._issue_date = value;
					this.SendPropertyChanged("issue_date");
					this.Onissue_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_return_date", DbType="DateTime NOT NULL")]
		public System.DateTime return_date
		{
			get
			{
				return this._return_date;
			}
			set
			{
				if ((this._return_date != value))
				{
					this.Onreturn_dateChanging(value);
					this.SendPropertyChanging();
					this._return_date = value;
					this.SendPropertyChanged("return_date");
					this.Onreturn_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bookcopy_mast_trans_mast", Storage="_bookcopy_mast", ThisKey="bk_id,bk_seq_id", OtherKey="bk_id,bk_seqno", IsForeignKey=true)]
		public bookcopy_mast bookcopy_mast
		{
			get
			{
				return this._bookcopy_mast.Entity;
			}
			set
			{
				bookcopy_mast previousValue = this._bookcopy_mast.Entity;
				if (((previousValue != value) 
							|| (this._bookcopy_mast.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bookcopy_mast.Entity = null;
						previousValue.trans_masts.Remove(this);
					}
					this._bookcopy_mast.Entity = value;
					if ((value != null))
					{
						value.trans_masts.Add(this);
						this._bk_id = value.bk_id;
						this._bk_seq_id = value.bk_seqno;
					}
					else
					{
						this._bk_id = default(decimal);
						this._bk_seq_id = default(decimal);
					}
					this.SendPropertyChanged("bookcopy_mast");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
